<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'prestashop');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '123456');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', '66RQeBYBCvLgeqfIELvww7yLnYmvMNBpUQR4OfVUImiNbLYdZEXKpDjM');
define('_COOKIE_IV_', 'Cvp5eavV');
define('_PS_CREATION_DATE_', '2014-10-27');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'qeQQLQGVuTV9c2AbHqwks1aIZFxJSLnR');
define('_RIJNDAEL_IV_', 'pcB05+bt0CjGupLx2ulpbQ==');
